# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.6.8'  # type: str
__version_tuple__ = version_tuple = (2, 6, 8)  # type: tuple[int | str, ...]
